repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v1.19.0
    hooks:
      - id: cfn-python-lint
        args: [--ignore-checks=W]
        files: ^templates/.*\.yaml$

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.33.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
